#!setupTx

rule "":
    A = 1234

    createCasedProgressBarIwt(3, getAllPlayers(), "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
<fg00FFFFFF><txb667> BREAKTHROUGH UPDATE 8.3.0 FOR OVERPY!</fg>

For the FIRST TIME EVER, you can use lowercase text
in the Overwatch Workshop! No more shouting—just pure,
clean typography exactly how you want it. But that’s not all...

<fgFF00FFFF><txb666> DELVE INTO A NEW ERA OF OVERWATCH WORKSHOP TEXT</fg>

For the <fgFF0000FF>first time in history</fg>, the tapestry of text in Overwatch
Workshop expands beyond the rigid confines of ALL CAPS.
With the latest OverPy update, you can now weave
lowercase letters seamlessly into your creations,
unlocking a realm of expression never before possible.

<fg80FF00FF><tx248B> FULL SUPPORT FOR COLOR TAGS & TEXTURES!</fg>

Customize your text like <fg00FF00FF>NEVER BEFORE</fg> with
vibrant colors and eye-catching textures. Whether you’re
designing a sleek UI, creating immersive story elements,
or just flexing your creativity, this update changes everything.

<fgFF8000FF><tx1f70d> The future of Workshop text starts NOW!</fg>

The ultimate workshop update: <fgFF0000FF>lowercase text</fg>.".format(A), null, 1.5, Clip.NONE, Color.WHITE, ProgressWorldTextReeval.VISIBILITY_POSITION_VALUES_AND_COLOR, SpecVisibility.ALWAYS)
    B = 567
