settings {
    "gamemodes": {
        "skirmish": {}
    },
    "heroes": {
        "allTeams": {
            "shion": {
                "secondaryFireCooldown%": 113,
                "ability1Cooldown%": 81,
                "ability1Distance%": 110,
                "ability2Cooldown%": 86,
                "ability2Kb%": 119,
                "ability2Duration%": 83,
                "ability2Speed%": 109,
                "enableInfiniteUlt": true
            }
        }
    }
}
